# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppStore_KAKAOBANK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'RxSwift'
   pod 'RxCocoa'
   pod 'Then'
   pod 'Alamofire'
   pod 'SnapKit', '~> 5.0.0'
   pod 'Kingfisher', '~> 5.15.8'
   pod 'Then'
   pod 'Cosmos'

  # Pods for AppStore_KAKAOBANK

end
